je-me-presente/je-me-presente/config/routes.rb
Rails.application.routes.draw do
  

	root 'static_pages#home'

  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  get '/about/etienne', to: 'static_pages#etienne', as: 'etienne'
  get '/about/claire', to: 'static_pages#claire', as: 'claire'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

je-me-presente/je-me-presente/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

je-me-presente/je-me-presente/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

je-me-presente/je-me-presente/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def claire
  end

  def etienne
  end


end

je-me-presente/je-me-presente/app/helpers/application_helper.rb
module ApplicationHelper
end

je-me-presente/je-me-presente/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

je-me-presente/je-me-presente/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Les Hackers sans Limite</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

je-me-presente/je-me-presente/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-0.8.1.min.css"/>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

	<%= render 'layouts/footer' %>

  </body>
</html>

je-me-presente/je-me-presente/app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<%=  link_to 'about Etienne', etienne_path %>
</br>
<%=  link_to 'about Claire', claire_path  %>

je-me-presente/je-me-presente/app/views/static_pages/claire.html.erb
<h1>About Claire</h1>
<p>More info about Claire here</p>

je-me-presente/je-me-presente/app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

je-me-presente/je-me-presente/app/views/static_pages/etienne.html.erb
<h1>About Etienne</h1>
<p>More info about Etienne here</p>

je-me-presente/je-me-presente/app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>bienvenue sur mon site lol mdr 😇❤️😻</p>